#!/bin/bash
# This program was modified from usplash package (/usr/share/initramfs-tools/hooks/usplash) of Debian by Steven Shiau on 2009/Aug/25

PREREQ="kernelextras"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

[ -x /sbin/usplash ] || exit 0

# Load functions
. /usr/lib/mkpxeinitrd-net/bin/mkpxeinitrd-net-func

mkdir -p ${DESTDIR}/usr/lib/usplash

copy_exec_not_link /sbin/usplash /sbin
copy_exec_not_link /sbin/usplash_write /sbin

if [ -f /etc/usplash.conf ]; then
	copy_exec_not_link /etc/usplash.conf /etc
fi

if [ -f /usr/lib/usplash/usplash-artwork.so ]; then
    copy_exec_not_link /usr/lib/usplash/usplash-artwork.so /usr/lib/usplash
fi
